### ISSUE TITLE
Empty _cachedStrings 

### ISSUE THREAD

**Issue by gabmarfer** [Baglan/MCLocalization#11]
### Description of the issue:
If you call [MCLocalization sharedInstance] before loading a JSON file and try to set English language, no string is returned.

### Cause:
I found out that you are creating a dummy datasource in the _initializer_ with English as supported language, but you have a condition in `setLanguage:` that skips the new setting if the language has already be set `if (![sanitizedLanguage isEqualToString:_language]) `

### Solutions:
Remove the dummy datasource from the _initializer_ or create it with a non valid language.

### Temporal fix:
Just set the datasource to nil after calling [MCLocalization sharedInstance] by first time. For instance, if you want to set a noKeyPlaceholder before loading a JSON:
` [MCLocalization sharedInstance].noKeyPlaceholder = @"'{key}'";`
` [MCLocalization sharedInstance].dataSource = nil; // Fix bug with dummy datasource of MCLocalization`

Thanks!

**Comment by Baglan** [comment]
Hi,

"Conventional" solution here would be to supply the dataSource before you access the "language" property (which triggers caching of the strings).

I can't be sure because I don't know the particulars of the scenario you are using this library in, but I've, possibly, fixed the issue by separating caching strings to a separate method ([MCLocalization reloadStrings]) and calling it both when language and dataSource change. Please let me know whether you encounter issues with this update.

As a side note, the root of this issue is that this library was initially designed to be used with a single JSON file containing multiple languages loaded at the initialization stage. Current state is a result of accommodating feature requests but these requests pulled the library in different directions that required solutions that seem less than reasonable (like initializing with a dummy data source).

This project outgrew it's initial purpose and it's hard to keep it compatible with older versions on the API level while fixing architectural issues or adding functionality. In my new apps I'm using https://github.com/Baglan/MCLocalization2 and I encourage you to have a look.

I haven't yet written documentation for it but it's used in production. The API is close to this project and it supports multiple prioritized data sources, including remote data sources and built-in localization.

One possible shortcoming is that it's written in Swift.

**Comment by gabmarfer** [comment]
The fix works correctly. Thanks!
