### ISSUE TITLE
perfomance

### ISSUE THREAD

**Issue by syrakozz** [Baglan/MCLocalization#5]
is this library good for performance, because in case the project was big he is loading the whole JSON file into the memory, right ? , is there any tricks to only load the necessary part, or if it was into plist or something it would be better, 
or perexample seperate the file by lang, so the app only load the english version of the file not the whole file
what do you think

**Comment by Baglan** [comment]
Hi,

I haven't encountered any noticeable performance issues but I've only used it with 2 widely distributed apps. The biggest file I'm currently using with this library is a 277K. The file is loaded in application:didFinishLaunchingWithOptions: and strings are kept in memory after that so any slowdown should only be on the application launch; because so many things happen on launch, it's hard to isolate this particular performance issue is there is one.

Because strings are kept in memory, it could, potentially, put unnecessary strain on device resources. The apps we make tend to be rather heavy on graphics so, I'm afraid, a few NSDictionarys and 2500 pairs of strings don't make much of a dent.

That said, I've thought about loading language-specific strings, say, on language change. I'm not sure when I would be able to implement such a thing though so, I suggest you to try to load all the languages first and see if you run into performance or memory issues.

Could you tell me, why did you decide to use this library instead of localization support supplied by Apple?

Cheers,
–Baglan

**Comment by syrakozz** [comment]
i use it for the "on the fly" feature

**Comment by Baglan** [comment]
I see. I'll think about it.

**Comment by Baglan** [comment]
Ok, I've added an ability to use multiple files. See https://github.com/Baglan/MCLocalization/blob/master/README.md#usage and https://github.com/Baglan/MCLocalization/blob/master/MCLocalization/AppDelegate.m#L24-L28 for details.

**Comment by syrakozz** [comment]
tx :)
