### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by ntsh** [Baglan/MCLocalization#6]
Do you know if there are any android  / Java port (or something similar) for this library?

**Comment by Baglan** [comment]
Hi,

I'm not aware of something similar but, then, I'm not a Java programmer. The functionality should be fairly straightforward to implement. Let me know if you decide to do that and I'll walk you through it – beats reading code in an unfamiliar language :).

As a general point, I would suggest you to look for more standard localization solutions as they tend to support many more features, such as pluralization or localization processes built around them. In particular, many localization companies work directly with files used by iOS and Android SDK's – that saves a lot of effort when exporting and re-importing strings.

**Comment by ntsh** [comment]
Thanks. I did look at other libraries. But yours was very simple to understand and get started. I have used MCLocalization in my iOS app, so wanted to have the same server localize file for the android app.

I have created a basic library for android here: https://github.com/ntsh/JsonLocalization

Please let me know what you think about it. Have tried to follow similar method names as yours.

**Comment by Baglan** [comment]
It has been a while since I've done any Java programming but seems reasonable enough. Good luck with the project!

p.s. I'm not familiar with file IO in Java so, perhaps, there are guards against it, but this looks like a possibility for a buffer overflow: https://github.com/ntsh/JsonLocalization/blob/master/jsonlocalization/src/main/java/com/walletcircle/jsonlocalization/JsonLocalization.java#L51

**Comment by ntsh** [comment]
Oh yeah. Totally forgot about the hard-coded size.

Thanks.
